// <auto-generated />
// Do not edit this file, changes will be overwritten.
namespace Allors.Workspace.Domain
{
    public partial class C2
    {
        public override string ToString() => this.ExistName ? this.Name : $"{this.Strategy.Class.SingularName}:{this.Strategy.Id}";
    }
}
